### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'dropout_W') in SimpleRNN function

### ISSUE THREAD

**Issue by HuaizhenC** [KordingLab/Neural_Decoding#12]
Hi I run the my_RNN_classifier.fit function in the central_concepts_in_ML_for_decoding.ipynb
I installed the Keras package version 2.3.0-tf, in which there is no dropout_W argument in the SimpleRNN function, would you mind telling which versions of keras and tensorflow I need to install to run this code, and are you gonna to update the code to be compatible to the more updated Keras and tensorflow versions?  
Thanks!

**Comment by jglaser2** [comment]
Hi, this worked as recently as Keras version 2.2.4. 

If you don't want to install this older version, within the decoders.py file, you can change "dropout_W" to "dropout" and "dropout_U" to "recurrent_dropout".

I do plan on updating the code to make it compatible with updated versions, but this won't happen for at least a few days.

**Comment by jglaser2** [comment]
The code has been updated to be compatible with the updated Keras/TF version.
