### ISSUE TITLE
save data for python examples in another format

### ISSUE THREAD

**Issue by neuromusic** [KordingLab/Neural_Decoding#4]
it's incredibly dangerous for users like myself to trust the pickle files that you've shared.

see e.g. https://www.cs.uic.edu/~s/musings/pickle/

can you convert these to HDF5? (try deepdish.io: http://deepdish.readthedocs.io/en/latest/io.html)

**Comment by jglaser2** [comment]
Thanks for the feedback. I'll try to do this in the next few days. 

In the meantime, you can take the ".mat" file I have also shared, and run it through the "Example_format_data" notebook to get the python file I have pickled.

**Comment by jglaser2** [comment]
The files are also all in '.h5' format now: https://www.dropbox.com/sh/n4924ipcfjqc0t6/AACPWjxDKPEzQiXKUUFriFkJa?dl=0
